ALTER TABLE public.work_blocks
  ADD COLUMN IF NOT EXISTS is_catch_up BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS planned_break_minutes INT NOT NULL DEFAULT 15,
  ADD COLUMN IF NOT EXISTS pause_count INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pause_minutes INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS task_snapshot JSONB;
